

version: "3"

services:


  mongodb:
    build : mongo/
    container_name: MongoDBContainer
    env_file:
      - ./.env
    environment:
      - MONGO_USER=$MONGO_USER
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_DB=$MONGO_DB
      - MONGO_PORT=$MONGO_PORT
    ports:
      - "27017:${MONGO_PORT}"
    volumes:
      - ./mongo/data_volume:/data/db


  rest_api_app:
    container_name: restAPIApp
    restart: always
    env_file:
      - ./.env
    environment:
      - APP_WORKING_DIR=$APP_WORKING_DIR
      - REST_API_APP_PORT=$REST_API_APP_PORT
    build: restAPI/
    ports:
      - "${REST_API_OUTER_APP_PORT}:${REST_API_APP_PORT}"
    depends_on:
      - mongodb

